/**
 * Theme packs as data (no fs). Raw values live only here — widgets must use CSS vars.
 * TODO(design-contract): replace with DTCG JSON compiled by the real package.
 */

export const lakehouseStudio = {
  id: "lakehouse-studio",
  name: "LakeHouse Studio",
  contractVersion: "0.1.0",
  colorScheme: "dark",
  description:
    "Brand default theme — dark neutral base with a single accent. Marketing surfaces stay dark-only; user skins may diverge.",
  cssVars: {
    "--color-surface-canvas": "#1E1E1E",
    "--color-surface-panel": "#252526",
    "--color-text-primary": "#E8EEF5",
    "--color-text-muted": "#9AA7B5",
    "--color-accent": "#7DFFFF",
    "--color-border-default": "#3A3A3A",
    "--font-family-ui": '"IBM Plex Sans", "Segoe UI", sans-serif',
    "--font-size-title": "1.35rem",
    "--font-size-body": "1rem",
    "--font-size-small": "0.9rem",
    "--font-size-caption": "0.8rem",
    "--space-2xs": "0.35rem",
    "--space-xs": "0.45rem",
    "--space-sm": "0.5rem",
    "--space-md": "0.75rem",
    "--space-lg": "1rem",
    "--space-xl": "1.25rem",
    "--radius-control": "0px",
    "--size-sidebar": "200px",
    "--size-hairline": "1px",
    "--size-focus-ring": "2px",
    "--size-focus-ring-offset": "2px",
    "--size-shell-widget-min": "420px",
    "--size-shell-lead-max": "52rem",
    "--size-preview-aside": "280px",
    "--size-preview-main-min": "calc(100vh - 5rem)",
    "--size-preview-log-max": "50vh",
    "--breakpoint-preview-stack": "800px",
    "--font-letter-spacing-title": "0.02em",
    "--font-letter-spacing-label": "0.04em",
    "--font-letter-spacing-caps": "0.06em",
    "--font-line-height-body": "1.45",
    "--state-disabled-opacity": "0.45",
    "--comp-button-bg":
      "color-mix(in srgb, var(--color-accent) 16%, var(--color-surface-panel))",
    "--comp-button-border":
      "color-mix(in srgb, var(--color-accent) 55%, var(--color-border-default))",
    "--comp-button-fg": "var(--color-text-primary)",
    "--comp-button-hover-border": "var(--color-accent)",
    "--comp-button-hover-fg": "var(--color-accent)",
    "--comp-focus-ring": "var(--color-accent)",
    "--comp-shell-gradient":
      "radial-gradient(120% 80% at 10% 0%, color-mix(in srgb, var(--color-accent) 18%, transparent), transparent 55%)",
  },
};

export const lakeMorning = {
  id: "lake-morning",
  name: "Lake Morning",
  contractVersion: "0.1.0",
  colorScheme: "light",
  description:
    "Example light skin proving a full runtime reskin without rebuild. Not the brand default.",
  cssVars: {
    "--color-surface-canvas": "#F4F7FA",
    "--color-surface-panel": "#FFFFFF",
    "--color-text-primary": "#1A2330",
    "--color-text-muted": "#5A6B7D",
    "--color-accent": "#0B7A7A",
    "--color-border-default": "#C9D3DE",
    "--font-family-ui": '"IBM Plex Sans", "Segoe UI", sans-serif',
    "--font-size-title": "1.35rem",
    "--font-size-body": "1rem",
    "--font-size-small": "0.9rem",
    "--font-size-caption": "0.8rem",
    "--space-2xs": "0.35rem",
    "--space-xs": "0.45rem",
    "--space-sm": "0.5rem",
    "--space-md": "0.75rem",
    "--space-lg": "1rem",
    "--space-xl": "1.25rem",
    "--radius-control": "0px",
    "--size-sidebar": "200px",
    "--size-hairline": "1px",
    "--size-focus-ring": "2px",
    "--size-focus-ring-offset": "2px",
    "--size-shell-widget-min": "420px",
    "--size-shell-lead-max": "52rem",
    "--size-preview-aside": "280px",
    "--size-preview-main-min": "calc(100vh - 5rem)",
    "--size-preview-log-max": "50vh",
    "--breakpoint-preview-stack": "800px",
    "--font-letter-spacing-title": "0.02em",
    "--font-letter-spacing-label": "0.04em",
    "--font-letter-spacing-caps": "0.06em",
    "--font-line-height-body": "1.45",
    "--state-disabled-opacity": "0.45",
    "--comp-button-bg":
      "color-mix(in srgb, var(--color-accent) 12%, var(--color-surface-panel))",
    "--comp-button-border":
      "color-mix(in srgb, var(--color-accent) 45%, var(--color-border-default))",
    "--comp-button-fg": "var(--color-text-primary)",
    "--comp-button-hover-border": "var(--color-accent)",
    "--comp-button-hover-fg": "var(--color-accent)",
    "--comp-focus-ring": "var(--color-accent)",
    "--comp-shell-gradient":
      "radial-gradient(120% 80% at 10% 0%, color-mix(in srgb, var(--color-accent) 14%, transparent), transparent 55%)",
  },
};
